version: "3.8"
services:
  api:
    build: ./api
    ports: 
      - "5000:5000"
    volumes:
      - type: bind
        source: ${API_SOURCE}
        target: /app
    environment: 
      FLASK_ENV: development
  client:
    build: ./client
    ports:
    - "3000:3000"
    volumes:
      - type: bind
        source: ${CLIENT_SOURCE}
        target: /app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: "redis:alpine"