version: "3.8"
services:
  api:
    build: ./api
    ports: 
      - "5000:5000"
    volumes:
      - type: bind
        source: /home/andru/Development/MyProjs/Motivately/api
        target: /app
    environment: 
      FLASK_ENV: development
  client:
    build: ./client
    ports:
    - "3000:3000"
    volumes:
      - type: bind
        source: /home/andru/Development/MyProjs/Motivately/client
        target: /app
  database:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
  reddis:
    image: "redis:alpine"